# Artificial Neural Network for prediciting Camber and Toe extrema

## Install any missing libraries

In [160]:
!pip3 install openpyxl

## Import all libraries

In [161]:
import glob 
import random
import numpy as np
import pandas as pd
import math
import os
from sklearn.model_selection import train_test_split
from keras.models import Sequential
from keras.layers import Dense
from sklearn.preprocessing import MinMaxScaler
import tensorflow as tf

## Importing, Cleaning, and Preparing Data

In [162]:
files=glob.glob("data/*.xlsx",recursive=True)
population=[]
for i in range(0, len(files)):
    parent=pd.read_excel(files[i],header=None).values
    population.append(parent)
population=np.array(population,dtype=object)

In [163]:
all_geometry = []
all_results = []
for i in range(0, len(population)):
    pop = pd.DataFrame(population[i])
    pop = pop.drop(index=[20, 21], axis=0)
    geometry = pop.iloc[14:22, 1:4].values
    results = pop.iloc[82:96, 2:6].values
    all_geometry.append(geometry)
    all_results.append(results)
all_geometry = np.array(all_geometry)
all_results = np.array(all_results)

In [164]:
output=np.empty(shape=[all_results.shape[0],4])
for i in range(all_results.shape[0]):
    output[i,0]=max(all_results[i,:,0])
    output[i,1]=min(all_results[i,:,0])
    output[i,2]=max(all_results[i,:,1])
    output[i,3]=min(all_results[i,:,1])

In [165]:
X=all_geometry.reshape((all_geometry.shape[0], -1))
y=output
X=X.astype('float32')
y=y.astype('float32')

X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.3)

train_df=pd.DataFrame(X_train)
train_df[24]=y_train[:,0]
train_df[25]=y_train[:,1]
train_df[26]=y_train[:,2]
train_df[27]=y_train[:,3]
target=train_df[24:28]
train_df

0           1           2       3           4           5   \
0   3959.0 -180.000000  485.000000  4259.0 -180.000000  465.000000   
1   3942.5 -236.000000  495.420013  4259.0 -237.800003  465.000000   
2   3939.0 -180.000000  485.000000  4259.0 -180.000000  455.000000   
3   3945.0 -181.000000  485.000000  4266.0 -181.000000  460.000000   
4   3939.0 -236.000000  485.000000  4259.0 -236.000000  455.000000   
5   3938.0 -181.000000  485.000000  4266.0 -179.000000  460.000000   
6   3819.0 -248.850006  291.869995  4179.0 -242.660004  258.850006   
7   3819.0 -118.809998  305.279999  4179.0 -118.809998  306.309998   
8   4039.0 -180.000000  495.000000  4259.0 -180.000000  485.000000   
9   3933.5 -228.899994  484.820007  4249.0 -231.199997  468.589996   
10  4050.0 -200.000000  485.000000  4259.0 -180.000000  455.000000   
11  3939.0 -180.000000  485.000000  4259.0 -180.000000  455.000000   
12  4039.0 -180.000000  495.000000  4259.0 -180.000000  485.000000   
13  3819.0 -143.610001  228.929993  4179.0 -128.139999  175.279999   
14  3889.0 -323.000000  225.600006  4229.0 -390.000000  225.899994   
15  3939.0 -180.000000  475.000000  4259.0 -180.000000  465.000000   
16  3941.5 -236.000000  495.420013  4249.5 -237.800003  465.000000   
17  3931.5 -233.899994  484.820007  4259.0 -234.800003  468.589996   
18  3938.0 -180.000000  484.000000  4259.0 -180.000000  454.000000   
19  3969.0 -180.000000  475.000000  4219.0 -180.000000  465.000000   
20  3939.0 -180.000000  485.000000  4259.0 -180.000000  455.000000   
21  3941.5 -231.500000  496.320007  4259.0 -232.800003  461.589996   
22  3931.5 -232.899994  484.820007  4259.0 -234.800003  468.589996   
23  3939.0 -236.000000  495.000000  4259.0 -236.000000  455.000000   
24  3939.5 -236.000000  495.000000  4259.0 -237.000000  455.000000   
25  3940.0 -181.000000  485.000000  4259.0 -181.000000  455.000000   
26  3819.0 -162.190002  227.899994  4179.0 -103.379997  180.440002   
27  3931.5 -226.899994  483.820007  4269.0 -221.199997  478.589996   
28  3819.0 -159.089996  225.600006  4179.0  -95.120003  185.899994   
29  3939.0 -180.000000  485.000000  4260.0 -180.000000  460.000000   
30  3979.0 -236.000000  485.000000  4259.0 -236.000000  455.000000   
31  3819.0  313.000000  485.000000  4259.0 -180.000000  455.000000   
32  3931.5 -236.800003  495.820007  4239.5 -238.100006  469.000000   
33  3819.0 -313.000000  225.600006  4179.0 -280.000000  185.899994   

             6           7           8            9   ...           18  \
0   4082.000000 -463.500000  255.000000  4072.500000  ...  4031.500000   
1   4072.129883 -530.500000  265.350006  3942.500000  ...  4037.500000   
2   4082.000000 -464.500000  265.000000  4072.500000  ...  4031.500000   
3   4084.000000 -464.500000  255.000000  4070.500000  ...  4031.500000   
4   4082.000000 -520.500000  265.000000  4072.500000  ...  4031.500000   
5   4082.000000 -464.500000  253.000000  4070.500000  ...  4031.500000   
6   4092.000000 -494.410004  240.279999  4092.500000  ...  4214.500000   
7   4092.000000 -470.640015  191.789993  4092.500000  ...  4214.500000   
8   4082.000000 -463.500000  255.000000  4072.500000  ...  4031.500000   
9   4062.159912 -528.500000  261.450012  3946.300049  ...  4051.399902   
10  4082.000000 -464.500000  255.000000  4072.500000  ...  4031.500000   
11  4082.000000 -464.500000  255.000000  4072.500000  ...  4035.500000   
12  4082.000000 -463.500000  255.000000  4072.500000  ...  4035.500000   
13  4092.000000 -538.770020  175.490005  4092.500000  ...  4214.500000   
14  4132.000000 -663.500000  181.649994  3922.500000  ...  4264.500000   
15  4082.000000 -463.500000  255.000000  3942.500000  ...  4031.500000   
16  4075.120117 -531.500000  269.350006  3942.500000  ...  4037.500000   
17  4074.159912 -526.500000  261.450012  3938.500000  ...  4041.800049   
18  4081.000000 -464.500000  255.000000  4072.500000  ...  4030.500000   
19  4082.000000 -463.500000  255.000000  4042.500000  ...  4031.500000   
20 

## Scaling Data between 0 and 1

In [166]:
scaler = MinMaxScaler(feature_range=(0, 1))
scaled_train = scaler.fit_transform(train_df)

# Print out the adjustment that the scaler applied to the data
print("Note: Median values were scaled by multiplying by {:.10f} and adding {:.6f}".format(scaler.scale_[27], scaler.min_[27]))
multiplied_by = scaler.scale_[27]
added = scaler.min_[27]

scaled_train_df = pd.DataFrame(scaled_train, columns=train_df.columns.values)
scaled_train_df

Note: Median values were scaled by multiplying by 0.0204379857 and adding 1.000527


0         1         2         3         4         5         6   \
0   0.606062  0.224843  0.958186  0.888889  0.712154  0.935426  0.284077   
1   0.534632  0.136792  0.996676  0.888889  0.516142  0.935426  0.142754   
2   0.519482  0.224843  0.958186  0.888889  0.712154  0.903138  0.284077   
3   0.545456  0.223270  0.958186  0.966667  0.708763  0.919282  0.312714   
4   0.519482  0.136792  0.958186  0.888889  0.522246  0.903138  0.284077   
5   0.515152  0.223270  0.958186  0.966667  0.715545  0.919282  0.284077   
6   0.000000  0.116588  0.244792  0.000000  0.499661  0.269824  0.427261   
7   0.000000  0.321053  0.294326  0.000000  0.919662  0.423060  0.427261   
8   0.952381  0.224843  0.995124  0.888889  0.712154  1.000000  0.284077   
9   0.495672  0.147956  0.957521  0.777779  0.538524  0.947017  0.000000   
10  1.000000  0.193396  0.958186  0.888889  0.712154  0.903138  0.284077   
11  0.519482  0.224843  0.958186  0.888889  0.712154  0.903138  0.284077   
12  0.952381  0.224843  0.995124  0.888889  0.712154  1.000000  0.284077   
13  0.000000  0.282060  0.012300  0.000000  0.888022  0.000000  0.427261   
14  0.303030  0.000000  0.000000  0.555557  0.000000  0.163438  1.000000   
15  0.519482  0.224843  0.921247  0.888889  0.712154  0.935426  0.284077   
16  0.530304  0.136792  0.996676  0.783333  0.516142  0.935426  0.185570   
17  0.487013  0.140094  0.957521  0.888889  0.526316  0.947017  0.171818   
18  0.515152  0.224843  0.954492  0.888889  0.712154  0.899910  0.269760   
19  0.649351  0.224843  0.921247  0.444443  0.712154  0.935426  0.284077   
20  0.519482  0.224843  0.958186  0.888889  0.712154  0.903138  0.284077   
21  0.530304  0.143868  1.000000  0.888889  0.533098  0.924416  0.114548   
22  0.487013  0.141667  0.957521  0.888889  0.526316  0.947017  0.143181   
23  0.519482  0.136792  0.995124  0.888889  0.522246  0.903138  0.140892   
24  0.521646  0.136792  0.995124  0.888889  0.518855  0.903138  0.143326   
25  0.523809  0.223270  0.958186  0.888889  0.708763  0.903138  0.255440   
26  0.000000  0.252846  0.008496  0.000000  0.971989  0.016660  0.427261   
27  0.487013  0.151101  0.953827  1.000000  0.572436  0.979304  0.143181   
28  0.000000  0.257720  0.000000  0.000000  1.000000  0.034289  0.427261   
29  0.519482  0.224843  0.958186  0.900002  0.712154  0.919282  0.284077   
30  0.692642  0.136792  0.958186  0.888889  0.522246  0.903138  0.284077   
31  0.000000  1.000000  0.958186  0.888889  0.712154  0.903138  0.284077   
32  0.487013  0.135535  0.998153  0.672222  0.515125  0.948340  0.099659   
33  0.000000  0.015723  0.000000  0.000000  0.373033  0.034289  0.427261   

          7         8         9   ...        18        19        20        21  \
0   0.848370  0.859658  0.882353  ...  0.004274  0.653971  0.733932  0.315790   
1   0.629752  0.960880  0.117647  ...  0.029915  0.506435  0.949408  0.003510   
2   0.845107  0.957457  0.882353  ...  0.004274  0.653971  0.805187  0.315790   
3   0.845107  0.859658  0.870588  ...  0.004274  0.653971  0.762434  0.315790   
4   0.662381  0.957457  0.882353  ...  0.004274  0.533640  0.769560  0.175439   
5   0.845107  0.840098  0.870588  ...  0.004274  0.655279  0.741058  0.315790   
6   0.747512  0.715697  1.000000  ...  0.786325  0.638354  0.972566  1.000001   
7   0.825073  0.241467  1.000000  ...  0.786325  0.714032  0.112370  1.000001   
8   0.848370  0.859658  0.882353  ...  0.004274  0.653971  0.712555  0.298246   
9   0.636278  0.922738  0.139999  ...  0.089315  0.518991  1.000000  0.038597   
10  0.845107  0.859658  0.882353  ...  0.004274  0.653971  0.733932  0.315790   
11  0.845107  0.859658  0.882353  ...  0.021368  0.653971  0.733932  0.333334   
12  0.848370  0.859658  0.882353  ...  0.021368  0.653971  0.712555  0.298246   
13  0.602767  0.082054  1.000000  ...  0.786325  0.546013  0.057859  1.000001   
14  0.195778  0.142298  0.000000  ...  1.000000  0.235430  0.071255  1.000001   
15  0.848370  0.859658  0.117647  ...  0.004274  0.65

## ANN Model

In [167]:
model = Sequential()

model.add(Dense(50, activation='relu'))
model.add(Dense(100, activation='relu'))
model.add(Dense(50, activation='relu'))
model.add(Dense(4))

model.compile(loss='mean_squared_error', optimizer='adam', metrics=['accuracy'])

In [168]:
X = scaled_train_df[scaled_train_df.columns[:24]].values
Y = scaled_train_df[scaled_train_df.columns[24:28]].values

In [169]:
model.fit(
    X,
    Y,
    epochs=1000,
    batch_size=10,
    shuffle=False,
    verbose=1
)

Epoch 1/1000
4/4 [==============================] - 1s 2ms/step - loss: 0.4059 - accuracy: 0.1739
Epoch 2/1000
4/4 [==============================] - 0s 2ms/step - loss: 0.2175 - accuracy: 0.1739
Epoch 3/1000
4/4 [==============================] - 0s 2ms/step - loss: 0.1116 - accuracy: 0.1739
Epoch 4/1000
4/4 [==============================] - 0s 4ms/step - loss: 0.0573 - accuracy: 0.1739
Epoch 5/1000
4/4 [==============================] - 0s 3ms/step - loss: 0.0400 - accuracy: 0.3029
Epoch 6/1000
4/4 [==============================] - 0s 5ms/step - loss: 0.0392 - accuracy: 0.7859
Epoch 7/1000
4/4 [==============================] - 0s 6ms/step - loss: 0.0340 - accuracy: 0.7859
Epoch 8/1000
4/4 [==============================] - 0s 5ms/step - loss: 0.0314 - accuracy: 0.7859
Epoch 9/1000
4/4 [==============================] - 0s 6ms/step - loss: 0.0341 - accuracy: 0.7859
Epoch 10/1000
4/4 [==============================] - 0s 5ms/step - loss: 0.0334 - accuracy: 0.3463
Epoch 11/1000
4/4 [

## Predictions

In [170]:
prediction = model.predict(X[:5])
print('Prediction with scaling - ',format(prediction))

y_pred = prediction
y_pred -= added
y_pred /= multiplied_by
print("Prediction - ",format(y_pred))

Prediction with scaling -  [[0.03107423 0.882997   0.00132065 0.97280717]
 [0.04412176 0.96538466 0.08537828 1.0032953 ]
 [0.03520633 0.94986063 0.00753495 0.98952293]
 [0.23113078 0.7458127  0.2343458  0.8185335 ]
 [0.04014774 0.95451266 0.00110839 0.9965549 ]]
Prediction -  [[-47.433884    -5.750581   -48.889683    -1.3563026 ]
 [-46.79549     -1.7194748  -44.776867     0.13543603]
 [-47.23171     -2.4790423  -48.585625    -0.5384253 ]
 [-37.645416   -12.462801   -37.48811     -8.904683  ]
 [-46.989933    -2.2514257  -48.900066    -0.19436121]]


In [171]:
Y[:5]

array([[0.04223196, 0.8674493 , 0.00384746, 0.97497976],
       [0.04048696, 0.9827057 , 0.09021953, 0.997621  ],
       [0.0403492 , 0.9500378 , 0.00982021, 0.9860776 ],
       [0.20426145, 0.81911695, 0.22853617, 0.8188172 ],
       [0.04069616, 0.9561312 , 0.00135424, 0.9950335 ]], dtype=float32)