In [16]:
!pip3 install openpyxl

     |████████████████████████████████| 243 kB 1.7 MB/s eta 0:00:01


In [235]:
import glob 
import random
import numpy as np
import pandas as pd
import math
import os
from sklearn.model_selection import train_test_split
from keras.models import Sequential
from keras.layers import Dense
from sklearn.preprocessing import MinMaxScaler
import tensorflow as tf

In [236]:
files=glob.glob("data/*.xlsx",recursive=True)
population=[]
for i in range(0, len(files)):
    parent=pd.read_excel(files[i],header=None).values
    population.append(parent)
population=np.array(population,dtype=object)

In [237]:
all_geometry = []
all_results = []
for i in range(0, len(population)):
    pop = pd.DataFrame(population[i])
    pop = pop.drop(index=[20, 21], axis=0)
    geometry = pop.iloc[14:22, 1:4].values
    results = pop.iloc[82:96, 2:6].values
    all_geometry.append(geometry)
    all_results.append(results)
all_geometry = np.array(all_geometry)
all_results = np.array(all_results)

In [238]:
output=np.empty(shape=[all_results.shape[0],4])
for i in range(all_results.shape[0]):
    output[i,0]=max(all_results[i,:,0])
    output[i,1]=min(all_results[i,:,0])
    output[i,2]=max(all_results[i,:,1])
    output[i,3]=min(all_results[i,:,1])
output

array([[ 2.80000e-03, -1.16360e+00,  5.60000e-01, -7.07000e-01],
       [ 4.06660e+00, -3.82680e+00,  1.20752e+01, -8.36320e+00],
       [ 5.43100e-01, -1.19660e+00,  8.70090e+00, -3.08400e-01],
       [ 1.44000e-02, -1.06190e+00,  7.54500e-01, -6.83500e-01],
       [ 1.00400e-01, -8.57900e-01,  7.92000e-02, -4.91300e-01],
       [ 4.07000e-02, -8.47200e-01,  5.46400e-01, -4.15000e-01],
       [ 0.00000e+00, -1.68220e+00,  4.79940e+01, -7.21960e+01],
       [ 5.50000e-03, -8.48900e-01,  4.66830e+00, -1.42200e-01],
       [ 0.00000e+00, -8.29300e-01,  3.43300e+00, -1.38320e+00],
       [ 0.00000e+00, -1.24930e+00,  3.70940e+00, -1.56000e+00],
       [ 1.03600e-01, -8.66300e-01,  1.25000e-01, -3.66600e-01],
       [ 1.55600e-01, -1.47480e+00,  2.07700e+00, -1.37990e+00],
       [ 3.03400e-01, -2.52600e+00,  4.93140e+00, -4.08060e+00],
       [ 1.51000e-02, -1.06230e+00,  6.66200e-01, -6.86600e-01],
       [ 2.08000e-02, -1.01940e+00,  6.11000e-01, -6.17200e-01],
       [ 1.88790e+00, -3.

In [239]:
X=all_geometry.reshape((all_geometry.shape[0], -1))
y=output
X=X.astype('float32')
y=y.astype('float32')

X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.3)

train_df=pd.DataFrame(X_train)
train_df[24]=y_train[:,0]
train_df[25]=y_train[:,1]
train_df[26]=y_train[:,2]
train_df[27]=y_train[:,3]
target=train_df[24:28]
train_df

0           1           2       3           4           5   \
0   3938.0 -180.000000  484.000000  4259.0 -180.000000  454.000000   
1   3979.0 -236.000000  485.000000  4259.0 -236.000000  455.000000   
2   3945.0 -181.000000  485.000000  4266.0 -181.000000  460.000000   
3   3931.5 -233.899994  484.820007  4259.0 -234.800003  468.589996   
4   3969.0 -180.000000  475.000000  4219.0 -180.000000  465.000000   
5   3959.0 -180.000000  485.000000  4259.0 -180.000000  465.000000   
6   3942.5 -236.000000  495.420013  4259.0 -237.800003  465.000000   
7   3941.5 -236.000000  495.420013  4249.5 -237.800003  465.000000   
8   3939.0 -236.000000  495.000000  4259.0 -236.000000  455.000000   
9   3939.0 -180.000000  475.000000  4259.0 -180.000000  465.000000   
10  3938.0 -181.000000  485.000000  4266.0 -179.000000  460.000000   
11  3939.0 -180.000000  485.000000  4259.0 -180.000000  455.000000   
12  3941.5 -231.500000  496.320007  4259.0 -232.800003  461.589996   
13  3939.0 -180.000000  485.000000  4259.0 -180.000000  455.000000   
14  3939.0 -180.000000  485.000000  4260.0 -180.000000  460.000000   
15  4039.0 -180.000000  495.000000  4259.0 -180.000000  485.000000   
16  3939.0 -190.000000  485.000000  4259.0 -190.000000  455.000000   
17  3939.0 -236.000000  485.000000  4259.0 -236.000000  455.000000   
18  3931.5 -226.899994  483.820007  4269.0 -221.199997  478.589996   
19  3939.0 -180.000000  485.000000  4259.0 -180.000000  455.000000   
20  3940.0 -181.000000  485.000000  4259.0 -181.000000  455.000000   
21  3935.0 -180.000000  485.000000  4259.0 -180.000000  455.000000   
22  3819.0  313.000000  485.000000  4259.0 -180.000000  455.000000   
23  3931.5 -236.800003  495.820007  4239.5 -238.100006  469.000000   
24  4039.0 -180.000000  495.000000  4259.0 -180.000000  485.000000   
25  3933.5 -228.899994  484.820007  4249.0 -231.199997  468.589996   

             6           7           8            9   ...           18  \
0   4081.000000 -464.500000  255.000000  4072.500000  ...  4030.500000   
1   4082.000000 -520.500000  255.000000  4072.500000  ...  4031.500000   
2   4084.000000 -464.500000  255.000000  4070.500000  ...  4031.500000   
3   4074.159912 -526.500000  261.450012  3938.500000  ...  4041.800049   
4   4082.000000 -463.500000  255.000000  4042.500000  ...  4031.500000   
5   4082.000000 -463.500000  255.000000  4072.500000  ...  4031.500000   
6   4072.129883 -530.500000  265.350006  3942.500000  ...  4037.500000   
7   4075.120117 -531.500000  269.350006  3942.500000  ...  4037.500000   
8   4072.000000 -530.500000  265.000000  3932.500000  ...  4031.500000   
9   4082.000000 -463.500000  255.000000  3942.500000  ...  4031.500000   
10  4082.000000 -464.500000  253.000000  4070.500000  ...  4031.500000   
11  4082.000000 -464.500000  255.000000  4072.500000  ...  4031.500000   
12  4070.159912 -526.500000  265.350006  3938.500000  ...  4037.800049   
13  4082.000000 -464.500000  255.000000  4072.500000  ...  4031.500000   
14  4082.000000 -464.500000  255.000000  4072.500000  ...  4034.500000   
15  4082.000000 -463.500000  255.000000  4072.500000  ...  4031.500000   
16  4082.000000 -464.500000  255.000000  4072.500000  ...  4031.500000   
17  4082.000000 -520.500000  265.000000  4072.500000  ...  4031.500000   
18  4072.159912 -526.799988  261.450012  3941.379883  ...  4050.399902   
19  4082.000000 -464.500000  255.000000  4072.500000  ...  4035.500000   
20  4080.000000 -464.500000  255.000000  4070.500000  ...  4031.500000   
21  4082.000000 -464.500000  255.000000  4072.500000  ...  4031.500000   
22  4082.000000 -464.500000  255.000000  4072.500000  ...  4031.500000   
23  4069.120117 -530.580017  269.350006  3942.500000  ...  4038.899902   
24  4082.000000 -463.500000  255.000000  4072.500000  ...  4035.500000   
25  4062.159912 -528.500000  261.450012  3946.300049  ...  4051.399902   

            19          20           21     22          23       24      25  \
0  -490.500000  310.000000  4048.500000

In [240]:
scaler = MinMaxScaler(feature_range=(0, 1))
scaled_train = scaler.fit_transform(train_df)

# Print out the adjustment that the scaler applied to the total_earnings column of data
print("Note: median values were scaled by multiplying by {:.10f} and adding {:.6f}".format(scaler.scale_[27], scaler.min_[27]))
multiplied_by = scaler.scale_[27]
added = scaler.min_[27]

scaled_train_df = pd.DataFrame(scaled_train, columns=train_df.columns.values)
scaled_train_df

Note: median values were scaled by multiplying by 0.0204867236 and adding 1.002913


0         1         2         3         4         5         6   \
0   0.540909  0.103310  0.422138  0.800003  0.983079  0.000000  0.862640   
1   0.727272  0.001455  0.469042  0.800003  0.035533  0.032258  0.908432   
2   0.572727  0.101491  0.469042  0.940002  0.966159  0.193548  1.000000   
3   0.511364  0.005275  0.460600  0.800003  0.055837  0.470645  0.549454   
4   0.681818  0.103310  0.000000  0.000000  0.983079  0.354839  0.908432   
5   0.636364  0.103310  0.469042  0.800003  0.983079  0.354839  0.908432   
6   0.561363  0.001455  0.957787  0.800003  0.005076  0.354839  0.456497   
7   0.556818  0.001455  0.957787  0.610001  0.005076  0.354839  0.593414   
8   0.545454  0.001455  0.938086  0.800003  0.035533  0.032258  0.450562   
9   0.545454  0.103310  0.000000  0.800003  0.983079  0.354839  0.908432   
10  0.540909  0.101491  0.469042  0.940002  1.000000  0.193548  0.908432   
11  0.545454  0.103310  0.469042  0.800003  0.983079  0.032258  0.908432   
12  0.556818  0.009640  1.000000  0.800003  0.089679  0.244839  0.366302   
13  0.545454  0.103310  0.469042  0.800003  0.983079  0.032258  0.908432   
14  0.545454  0.103310  0.469042  0.820000  0.983079  0.193548  0.908432   
15  1.000000  0.103310  0.938086  0.800003  0.983079  1.000000  0.908432   
16  0.545454  0.085122  0.469042  0.800003  0.813875  0.032258  0.908432   
17  0.545454  0.001455  0.469042  0.800003  0.035533  0.032258  0.908432   
18  0.511364  0.018007  0.413696  1.000000  0.285956  0.793226  0.457886   
19  0.545454  0.103310  0.469042  0.800003  0.983079  0.032258  0.908432   
20  0.549999  0.101491  0.469042  0.800003  0.966159  0.032258  0.816849   
21  0.527273  0.103310  0.469042  0.800003  0.983079  0.032258  0.908432   
22  0.000000  1.000000  0.469042  0.800003  0.983079  0.032258  0.908432   
23  0.511364  0.000000  0.976547  0.410004  0.000000  0.483871  0.318695   
24  1.000000  0.103310  0.938086  0.800003  0.983079  1.000000  0.908432   
25  0.520454  0.014369  0.460600  0.599998  0.116751  0.470645  0.000000   

          7         8         9   ...        18        19        20        21  \
0   0.985294  0.122324  1.000000  ...  0.000000  0.991511  0.190114  0.926315   
1   0.161765  0.122324  1.000000  ...  0.047852  0.040748  0.000000  0.947369   
2   0.985294  0.122324  0.985714  ...  0.047852  0.991511  0.295733  0.947369   
3   0.073529  0.516820  0.042856  ...  0.540680  0.115451  0.913392  0.031578   
4   1.000000  0.122324  0.785713  ...  0.047852  0.991511  0.211238  0.947369   
5   1.000000  0.122324  1.000000  ...  0.047852  0.991511  0.211238  0.947369   
6   0.014706  0.755352  0.071428  ...  0.334930  0.033956  0.850021  0.010525   
7   0.000000  1.000000  0.071428  ...  0.334930  0.000000  0.744402  0.094738   
8   0.014706  0.733944  0.000000  ...  0.047852  0.040748  0.844951  0.000000   
9   1.000000  0.122324  0.071428  ...  0.047852  0.991511  0.211238  0.947369   
10  0.985294  0.000000  0.985714  ...  0.047852  1.000000  0.232361  0.947369   
11  0.985294  0.122324  1.000000  ...  0.047852  0.991511  0.211238  0.947369   
12  0.073529  0.755352  0.042856  ...  0.349289  0.101868  0.850021  0.042107   
13  0.985294  0.122324  1.000000  ...  0.047852  0.991511  0.211238  0.947369   
14  0.985294  0.122324  1.000000  ...  0.191391  0.966044  0.211238  0.947369   
15  1.000000  0.122324  1.000000  ...  0.047852  0.991511  0.147866  0.894737   
16  0.985294  0.122324  1.000000  ...  0.047852  0.991511  0.211238  0.947369   
17  0.161765  0.733944  1.000000  ...  0.047852  0.210526  0.316857  0.526314   
18  0.069118  0.516820  0.063427  ...  0.952148  0.081495  0.852979  0.013683   
19  0.985294  0.122324  1.000000  ...  0.239243  0.991511  0.211238  1.000000   
20  0.985294  0.122324  0.985714  ...  0.047852  0.991511  0.211238  0.947369   
21  0.985294  0.122324  1.000000  ...  0.047852  0.991511  0.211238  0.947369   
22  0.985294  0.122324  1.000000  ...  0.047852  0.991511  0.211238  0.947369   
23  0.013529 

In [251]:
model = Sequential()

model.add(Dense(50, activation='relu'))
model.add(Dense(100, activation='relu'))
model.add(Dense(50, activation='relu'))
model.add(Dense(4))

model.compile(loss='mean_squared_error', optimizer='adam', metrics=['accuracy'])

In [252]:
X = scaled_train_df[scaled_train_df.columns[:24]].values
Y = scaled_train_df[scaled_train_df.columns[24:28]].values

In [253]:
# Train the model
model.fit(
    X,
    Y,
    epochs=1000,
    shuffle=False,
    verbose=2
)

Epoch 1/1000
1/1 - 1s - loss: 0.6133 - accuracy: 0.0385
Epoch 2/1000
1/1 - 0s - loss: 0.4899 - accuracy: 0.1538
Epoch 3/1000
1/1 - 0s - loss: 0.3820 - accuracy: 0.5385
Epoch 4/1000
1/1 - 0s - loss: 0.2980 - accuracy: 0.5385
Epoch 5/1000
1/1 - 0s - loss: 0.2344 - accuracy: 0.5385
Epoch 6/1000
1/1 - 0s - loss: 0.1863 - accuracy: 0.5385
Epoch 7/1000
1/1 - 0s - loss: 0.1524 - accuracy: 0.5385
Epoch 8/1000
1/1 - 0s - loss: 0.1290 - accuracy: 0.5000
Epoch 9/1000
1/1 - 0s - loss: 0.1134 - accuracy: 0.1154
Epoch 10/1000
1/1 - 0s - loss: 0.1032 - accuracy: 0.1154
Epoch 11/1000
1/1 - 0s - loss: 0.0964 - accuracy: 0.1154
Epoch 12/1000
1/1 - 0s - loss: 0.0909 - accuracy: 0.1538
Epoch 13/1000
1/1 - 0s - loss: 0.0855 - accuracy: 0.5000
Epoch 14/1000
1/1 - 0s - loss: 0.0803 - accuracy: 0.5385
Epoch 15/1000
1/1 - 0s - loss: 0.0756 - accuracy: 0.5385
Epoch 16/1000
1/1 - 0s - loss: 0.0714 - accuracy: 0.5385
Epoch 17/1000
1/1 - 0s - loss: 0.0681 - accuracy: 0.6538
Epoch 18/1000
1/1 - 0s - loss: 0.0654 - 

In [254]:
prediction = model.predict(X[:10])
y_0 = prediction[1][0]
print('Prediction with scaling - ',format(y_0))
y_0 -= added
y_0 /= multiplied_by
print("Prediction - ",format(y_0))

Prediction with scaling -  0.0006229318678379059
Prediction -  -48.923892974853516


In [255]:
Y[:10]

array([[2.2836558e-03, 9.6195555e-01, 2.8211992e-02, 9.9441123e-01],
       [3.0299119e-04, 8.3063400e-01, 6.9518685e-02, 9.6379179e-01],
       [1.8040882e-01, 5.9798360e-01, 6.7483985e-01, 8.2076985e-01],
       [0.0000000e+00, 8.6918604e-01, 2.1099471e-01, 9.7095394e-01],
       [9.1514569e-03, 9.5408827e-01, 3.4516636e-02, 9.8727775e-01],
       [2.2275464e-03, 7.0540333e-01, 1.1361076e-02, 9.7730482e-01],
       [3.0860215e-04, 9.6156335e-01, 2.6640740e-01, 1.0000000e+00],
       [3.0473059e-02, 8.8134468e-01, 4.9944240e-01, 9.9659514e-01],
       [0.0000000e+00, 9.6608531e-01, 1.9502218e-01, 9.7457600e-01],
       [2.9120820e-03, 9.7741330e-01, 5.1067054e-02, 9.8104775e-01]],
      dtype=float32)

In [256]:
prediction

array([[2.0850077e-03, 9.4853956e-01, 2.2399666e-02, 9.9548304e-01],
       [6.2293187e-04, 8.2978308e-01, 6.9996633e-02, 9.6393198e-01],
       [1.8198860e-01, 5.9471053e-01, 6.7764372e-01, 8.2569927e-01],
       [4.3665618e-04, 8.6757952e-01, 2.1171840e-01, 9.7079396e-01],
       [9.6617714e-03, 9.5186692e-01, 3.5764944e-02, 9.8599601e-01],
       [3.6189780e-03, 7.0096272e-01, 1.5183510e-02, 9.8005325e-01],
       [6.3545629e-04, 9.5977676e-01, 2.6705328e-01, 9.9942636e-01],
       [3.1218536e-02, 8.7984180e-01, 5.0028318e-01, 9.9646121e-01],
       [1.2303144e-04, 9.6433926e-01, 1.9567035e-01, 9.7419775e-01],
       [3.4509674e-03, 9.7520083e-01, 5.2221898e-02, 9.8006523e-01]],
      dtype=float32)